### ISSUE TITLE
Not sure if this will help.

### ISSUE THREAD

**Issue by JamesDrummond** [segator/scaleway-sdk#1]
I work for codenvy and have used scaleways to launch our IDE. Take a look at this document. May make your programming life easier.

[https://docs.google.com/document/d/1kjJPIuSIBHvvs2ii-_N-I-ywBTOKVPEJL6RRpSOEz1Q/pub](https://docs.google.com/document/d/1kjJPIuSIBHvvs2ii-_N-I-ywBTOKVPEJL6RRpSOEz1Q/pub)

**Comment by segator** [comment]
Thank you very much its seems interesting but For now I work with Netbeans, I feel more confortable
